# BEAUTYPRICE INTELLIGENCE — EDA
Notebook riêng cho Nhiệm vụ 1, Giai đoạn 6. Chạy Run All để đọc CSV thật, tạo lại `01_ket_qua_eda.xlsx` và hiển thị kết quả.

In [1]:
from pathlib import Path
import runpy, sys, pandas as pd
candidates=[Path.cwd(),Path.cwd()/'BDr'/'kqptr',Path.cwd()/'kqptr']
folder=next(p for p in candidates if (p/'01_eda.py').is_file())
sys.path.insert(0,str(folder.resolve()))
g=runpy.run_path(str(folder/'01_eda.py'))

Created: C:\Users\Latitude 5500\OneDrive\Big Data\BDr\kqptr\01_ket_qua_eda.xlsx
Giá hợp lệ: 6,350; min=5,000; max=3,160,000; ngoại lệ IQR=314

## Tập dữ liệu, số quan sát và điều kiện lọc
Một dòng `price_snapshots` là một quan sát. Giá hợp lệ là số hữu hạn lớn hơn 0. Giá trống, sai kiểu, bằng 0 hoặc âm bị loại khỏi thống kê giá nhưng vẫn nằm trong mẫu số chất lượng.

In [2]:
pd.DataFrame(g['overview_rows'],columns=['Chỉ tiêu','Giá trị'])

                        Chỉ tiêu                           Giá trị
               Tập dữ liệu chính           price_snapshots (1).csv
                 Đơn vị quan sát             Một dòng snapshot giá
               Phạm vi thời gian 2026-10-18 đến 2026-10-21 (UTC+7)
                   Tổng snapshot                              6350
Sản phẩm duy nhất trong products                              5657
          Thương hiệu có giá trị                               442
    Danh mục trong bảng liên kết                                 6
                      Nhà bán lẻ                                 5
             Giá hiện tại hợp lệ                              6350
         Ngày thu thập thiếu/sai                                 0
               Snapshot_id trùng                                 0

## Thống kê mô tả
Bảng có số quan sát, tỷ lệ thiếu/không hợp lệ, giá thấp nhất, giá cao nhất, trung bình, trung vị, độ lệch chuẩn, Q1, Q3 và IQR.

In [3]:
g['numeric_frame']

                     variable                                    source  total_n  valid_n  missing_n  invalid_n  missing_invalid_rate_pct     min            q1          mean        median         q3          max           std           iqr  lower_bound  upper_bound  outlier_candidate_n  outlier_candidate_rate_pct  unit                                                                     filter_conditions
            current_price_vnd                   price_snapshots (1).csv     6350     6350          0          0                  0.000000  5000.0 145000.000000 316861.906142 244000.000000 406000.000 3.160000e+06 278083.631209 261000.000000    -246500.0     797500.0                314.0                    4.944882   VND                                     Finite current price > 0; IQR candidates retained
             listed_price_vnd                   price_snapshots (1).csv     6350     4861       1489          0                 23.448819 16000.0 202000.000000 440679.680724 350000.000000 555000.000 3.950000e+06 369924.852311 353000.000000          NaN          NaN                  NaN                         NaN   VND                                                               Finite listed price > 0
             discount_percent                   price_snapshots (1).csv     6350     4861       1489          0                 23.448819     0.0     15.060000     27.768655     24.980000     38.000 9.816000e+01     16.129147     22.940000          NaN          NaN                  NaN                         NaN     % Resolved input discount in [0,100]; original website value is discount_percent_source
  discount_percent_calculated                   price_snapshots (1).csv     6350     4861       1489          0                 23.448819     0.0     15.100000     27.771401     24.930000     38.120 9.816000e+01     16.126708     23.020000          NaN          NaN                  NaN                         NaN     %                                                 Source calculated discount in [0,100]
discount_percent_recalculated                   price_snapshots (1).csv     6350     4861       1489          0                 23.448819     0.0     15.102041     27.771416     24.926254     38.125 9.815951e+01     16.126671     23.022959          NaN          NaN                  NaN                         NaN     %                                  P>0; L>0; L>=P; exclude anomalous negative discounts
                       rating hasaki_reviews.csv + guardian_reviews.csv     6673     6673          0          0                  0.000000     2.5      5.000000      4.899820      5.000000      5.000 5.000000e+00      0.301321      0.000000          NaN          NaN                  NaN                         NaN stars                          All source review rows; range check 1–5; half stars retained

## Chất lượng dữ liệu
Không chỉ khảo sát giá: notebook thống kê giá trị trống theo mọi trường chính và các trạng thái thu thập, liên kết, giá và khuyến mãi.

In [4]:
display(g['categorical_frame'])
display(g['coverage_frame'])
display(pd.DataFrame(g['grouped_rows'],columns=g['group_headers']))

          source          variable                        value  count  percentage  unique_count  denominator_n
 price_snapshots             brand                       Cocoon    350    5.511811           442           6350
 price_snapshots             brand                      EUCERIN    192    3.023622           442           6350
 price_snapshots             brand                      Garnier    175    2.755906           442           6350
 price_snapshots             brand                         DOVE    146    2.299213           442           6350
 price_snapshots             brand                      SUNPLAY    143    2.251969           442           6350
 price_snapshots             brand               La Roche-Posay    121    1.905512           442           6350
 price_snapshots             brand                     BIODERMA    111    1.748031           442           6350
 price_snapshots             brand                        Vichy    108    1.700787           442           6350
 price_snapshots             brand                         OLAY    104    1.637795           442           6350
 price_snapshots             brand                    Hada Labo    104    1.637795           442           6350
 price_snapshots             brand                       CERAVE    101    1.590551           442           6350
 price_snapshots             brand                  Bio-essence     96    1.511811           442           6350
 price_snapshots             brand                     Cetaphil     94    1.480315           442           6350
 price_snapshots             brand                          SVR     89    1.401575           442           6350
 price_snapshots             brand                      L'Oreal     89    1.401575           442           6350
 price_snapshots             brand                        NIVEA     84    1.322835           442           6350
 price_snapshots             brand                       SIMPLE     82    1.291339           442           6350
 price_snapshots             brand                        SENKA     79    1.244094           442           6350
 price_snapshots             brand               PAULA'S CHOICE     74    1.165354           442           6350
 price_snapshots             brand                       ANESSA     72    1.133858           442           6350
 price_snapshots             brand                L'OREAL PARIS     71    1.118110           442           6350
 price_snapshots             brand                        BIORE     62    0.976378           442           6350
 price_snapshots             brand                     SKIN1004     59    0.929134           442           6350
 price_snapshots             brand                       d'Alba     55    0.866142           442           6350
 price_snapshots             brand                      BEPLAIN     53    0.834646           442           6350
 price_snapshots             brand                   Neutrogena     53    0.834646           442           6350
 price_snapshots             brand                     Torriden     49    0.771654           442           6350
 price_snapshots             brand                        ACNES     49    0.771654           442           6350
 price_snapshots             brand                   SOME BY MI     47    0.740157           442           6350
 price_snapshots             brand                        BIORÉ     46    0.724409           442           6350
 price_snapshots             brand                      ST.IVES     46    0.724409           442           6350
 price_snapshots             brand                     THORAKAO     43    0.677165           442           6350
 price_snapshots             brand                       MIZUMI     42    0.661417           442           6350
 price_snapshots             brand                     Lifebuoy     42    0.661417           442           6350
 price_snapshots             brand                        Curél     40    0.629921           442           6350
 price_snapshots             brand             TESORI D'ORIENTE     40    0.629921           442           6350
 price_snapshots             brand                        B.O.M     40    0.629921           442           6350
 price_snapshots             brand                     COLORKEY     39    0.614173           442           6350
 price_snapshots             brand                    INNISFREE     38    0.598425           442           6350
 price_snapshots             brand                        OBAGI     36    0.566929           442           6350
 price_snapshots             brand                     VASELINE     36    0.566929           442           6350
 price_snapshots             brand                  DOUBLE RICH     36    0.566929           442           6350
 price_snapshots             brand               LA ROCHE POSAY     36    0.566929           442           6350
 price_snapshots             brand                     Hatomugi     35    0.551181           442           6350
 price_snapshots             brand                          BOM     35    0.551181           442           6350
 price_snapshots             brand                  DEAR KLAIRS     35    0.551181           442           6350
 price_snapshots             brand                       ELIXIR     35    0.551181           442           6350
 price_snapshots             brand                    SILKYGIRL     34    0.535433           442           6350
 price_snapshots             brand                    DrCeutics     32    0.503937           442           6350
 price_snapshots             brand                         KOSÉ     31    0.488189           442           6350
 price_snapshots             brand                      WATSONS     31    0.488189           442           6350
 price_snapshots             brand               ZAKKA NATURALS     30    0.472441           442           6350
 price_snapshots             brand                        COSRX     28    0.440945           442           6350
 price_snapshots             brand                      Unknown     28    0.440945           442           6350
 price_snapshots             brand                    ROUND LAB     27    0.425197           442           6350
 price_snapshots             brand                     NUMBUZIN     27    0.425197           442           6350
 price_snapshots             brand                    EVOLUDERM     27    0.425197           442           6350
 price_snapshots             brand                   COMPLIMENT     27    0.425197           442           6350
 price_snapshots             brand                    BANILA CO     26    0.409449           442           6350
 price_snapshots             brand                   ENCHANTEUR     25    0.393701           442           6350
 price_snapshots             brand              Naris Cosmetics     25    0.393701           442           6350
 price_snapshots             brand                      L'Oréal     24    0.377953           442           6350
 price_snapshots             brand                    Old Spice     24    0.377953           442           6350
 price_snapshots             brand                       Klairs     23    0.362205           442           6350
 price_snapshots             brand                  BANANA BOAT     23    0.362205           442           6350
 price_snapshots             brand            MANNINGS GUARDIAN     23    0.362205           442           6350
 price_snapshots             brand          MAYBELLINE NEW YORK     23    0.362205           442           6350
 price_snapshots             brand                Cell Fusion C     22    0.346457           442           6350
 price_snapshots             brand                     Hazeline     22    0.346457           442           6350
 price_snapshots             brand                 Kiss My Body     22    0.346457           442           6350
 price_snapshots             brand                       CHANDO     22    0.346457           442           6350
 price_snapshots             brand                       MA:NYO     21    0.330709           442           6350
 price_snapshots             brand                       POND'S     21    0.330709           442           6350
 price_snapshots             brand                       AXIS-Y     21    0.330709           442           6350
 price_snapshots             brand                       Gennie     21    0.330709           442           6350
 price_snapshots             brand                      CELIMAX     20    0.314961           442           6350
 price_snapshots             brand                       JUMISO     19    0.299213           442           6350
 price_snapshots             brand                         ABIB     19    0.299213           442           6350
 price_snapshots             brand                  ON THE BODY     19    0.299213           442           6350
 price_snapshots             brand                      AZDERMA     19    0.299213           442           6350
 price_snapshots             brand                     BareSoul     19    0.299213           442           6350
 price_snapshots             brand                     DR.PEPTI     18    0.283465           442           6350
 price_snapshots             brand                     CARYOPHY     18    0.283465           442           6350
 price_snapshots             brand               Grace And Glow     18    0.283465           442           6350
 price_snapshots             brand                     CLINICOS     18    0.283465           442           6350
 price_snapshots             brand                     MEDIHEAL     18    0.283465           442           6350
 price_snapshots             brand       Balance Active Formula     18    0.283465           442           6350
 price_snapshots             brand                  Swiss Image     18    0.283465           442           6350
 price_snapshots             brand                   JMsolution     18    0.283465           442           6350
 price_snapshots             brand          COLLAGEN BY WATSONS     18    0.283465           442           6350
 price_snapshots             brand               CNP LABORATORY     17    0.267717           442           6350
 price_snapshots             brand                        X-MEN     16    0.251969           442           6350
 price_snapshots             brand             REIHAKU HATOMUGI     16    0.251969           442           6350
 price_snapshots             brand                       URIAGE     16    0.251969           442           6350
 price_snapshots             brand                         ANUA     16    0.251969           442           6350
 price_snapshots             brand                 On: The Body     16    0.251969           442           6350
 price_snapshots             brand                      BIFESTA     16    0.251969           442           6350
 price_snapshots             brand                          OXY     15    0.236220           442           6350
 price_snapshots             brand               Angel's Liquid     15    0.236220           442           6350
 price_snapshots             brand                      YUKAZAN     15    0.236220           442           6350
 price_snapshots             brand                    MELANO CC     15    0.236220           442           6350
 price_snapshots             brand                Cetaphil Baby     15    0.236220           442           6350
 price_snapshots             brand                      The Lab     15    0.236220           442           6350
 price_snapshots             brand                       DINSEE     15    0.236220           442           6350
 price_snapshots             brand                          CNP     14    0.220472           442           6350
 price_snapshots             brand                       ROMANO     14    0.220472           442           6350
 price_snapshots             brand               CANCER COUNCIL     14    0.220472           442           6350
 price_snapshots             brand                     CARE:NEL     14    0.220472           442           6350
 price_snapshots             brand                     dProgram     14    0.220472           442           6350
 price_snapshots             brand                    D PROGRAM     14    0.220472           442           6350
 price_snapshots             brand                     BANOBAGI     14    0.220472           442           6350
 price_snapshots             brand                MISE EN SCÈNE     14    0.220472           442           6350
 price_snapshots             brand                  CINDY BLOOM     13    0.204724           442           6350
 price_snapshots             brand                      MD CARE     13    0.204724           442           6350
 price_snapshots             brand                          COW     13    0.204724           442           6350
 price_snapshots             brand                          LUX     13    0.204724           442           6350
 price_snapshots             brand                    PALMOLIVE     13    0.204724           442           6350
 price_snapshots             brand             Neogen Dermalogy     13    0.204724           442           6350
 price_snapshots             brand                      Actidem     13    0.204724           442           6350
 price_snapshots             brand                    REVOX B77     13    0.204724           442           6350
 price_snapshots             brand                        COOPY     12    0.188976           442           6350
 price_snapshots             brand                         DR.G     12    0.188976           442           6350
 price_snapshots             brand                         mine     12    0.188976           442           6350
 price_snapshots             brand                  EMBRYOLISSE     12    0.188976           442           6350
 price_snapshots             brand                     TRESEMME     12    0.188976           442           6350
 price_snapshots             brand                        KOTEX     12    0.188976           442           6350
 price_snapshots             brand                    D-PROGRAM     12    0.188976           442           6350
 price_snapshots             brand              Corine de Farme     12    0.188976           442           6350
 price_snapshots             brand                  BRING GREEN     12    0.188976           442           6350
 price_snapshots             brand                       Shimbi     12    0.188976           442           6350
 price_snapshots             brand                         NUXE     12    0.188976           442           6350
 price_snapshots             brand                    DERMARIUM     12    0.188976           442           6350
 price_snapshots             brand                      ROSETTE     11    0.173228           442           6350
 price_snapshots             brand                     ST. IVES     11    0.173228           442           6350
 price_snapshots             brand                     Lactacyd     11    0.173228           442           6350
 price_snapshots             brand                       Nerman     11    0.173228           442           6350
 price_snapshots             brand                       BEYOND     10    0.157480           442           6350
 price_snapshots             brand               ROGER & GALLET     10    0.157480           442           6350
 price_snapshots             brand                      9Wishes     10    0.157480           442           6350
 price_snapshots             brand                     TREE HUT     10    0.157480           442           6350
 price_snapshots             brand                        LASHE     10    0.157480           442           6350
 price_snapshots             brand                       KISSME     10    0.157480           442           6350
 price_snapshots             brand                       PURITE     10    0.157480           442           6350
 price_snapshots             brand                   Moaw Moaws     10    0.157480           442           6350
 price_snapshots             brand                     BIOVERSE     10    0.157480           442           6350
 price_snapshots             brand                      ARRAHAN      9    0.141732           442           6350
 price_snapshots             brand                       HETRAS      9    0.141732           442           6350
 price_snapshots             brand                    Martiderm      9    0.141732           442           6350
 price_snapshots             brand                     I'm from      9    0.141732           442           6350
 price_snapshots             brand                       MISSHA      9    0.141732           442           6350
 price_snapshots             brand            LABORATORIOS BABÉ      9    0.141732           442           6350
 price_snapshots             brand           Purité By Prôvence      9    0.141732           442           6350
 price_snapshots             brand                     9 Wishes      9    0.141732           442           6350
 price_snapshots             brand                     Sensilis      9    0.141732           442           6350
 price_snapshots             brand                       PURITO      9    0.141732           442           6350
 price_snapshots             brand        TARGET PRO BY WATSONS      9    0.141732           442           6350
 price_snapshots             brand                      SEBAMED      9    0.141732           442           6350
 price_snapshots             brand                  JM SOLUTION      8    0.125984           442           6350
 price_snapshots             brand           Exclusive Cosmetic      8    0.125984           442           6350
 price_snapshots             brand                       ESPOIR      8    0.125984           442           6350
 price_snapshots             brand                  BABY BRIGHT      8    0.125984           442           6350
 price_snapshots             brand                     CLOSE UP      8    0.125984           442           6350
 price_snapshots             brand                     Gervenne      8    0.125984           442           6350
 price_snapshots             brand                     THE SAEM      8    0.125984           442           6350
 price_snapshots             brand                     HIMALAYA      8    0.125984           442           6350
 price_snapshots             brand                        BELIF      8    0.125984           442           6350
 price_snapshots             brand                         NUSE      8    0.125984           442           6350
 price_snapshots             brand                         JOMI      8    0.125984           442           6350
 price_snapshots             brand                     Derladie      7    0.110236           442           6350
 price_snapshots             brand                   Shu Uemura      7    0.110236           442           6350
 price_snapshots             brand                        TIA'M      7    0.110236           442           6350
 price_snapshots             brand                    AROMATICA      7    0.110236           442           6350
 price_snapshots             brand                        CINDY      7    0.110236           442           6350
 price_snapshots             brand                         OHUI      7    0.110236           442           6350
 price_snapshots             brand                     GILLETTE      7    0.110236           442           6350
 price_snapshots             brand                      PANTENE      7    0.110236           442           6350
 price_snapshots             brand                       Avatar      7    0.110236           442           6350

   scope                                     metric                     value                                                                definition
   PRICE                      total_price_snapshots                      6350                                                   All input snapshot rows
   PRICE                          unique_product_id                      5657                                                  Unique snapshot products
   PRICE                     master_unique_products                      5657                          Products master; distinct from snapshot products
   PRICE                              unique_brands                       442                   Nonblank snapshot brand strings; no alias normalization
   PRICE                  unique_primary_categories                         6                       Nonblank primary_category; missing shown separately
   PRICE                   unique_linked_categories                         6                            Distinct labels in category relationship table
   PRICE                           unique_retailers                         5                                               Distinct retailers observed
   PRICE                      earliest_collected_at 2026-10-18 07:09:23+07:00                                                                     UTC+7
   PRICE                        latest_collected_at 2026-10-21 19:05:49+07:00                                                                     UTC+7
   PRICE                             observed_dates                         4                                             Distinct observed local dates
   PRICE                      duplicate_snapshot_id                         0                                                      Excess duplicate IDs
   PRICE                        duplicate_full_rows                         0                                                     Excess identical rows
   PRICE                      missing_current_price                         0                                                             Blank/NA only
   PRICE                      invalid_current_price                         0                                         Nonblank nonnumeric/nonfinite/<=0
   PRICE                       missing_listed_price                      1489                                                             Blank/NA only
   PRICE                           missing_discount                      1489                                                             Blank/NA only
   PRICE                         anomalous_discount                         0                         P>0 and L>0 but L<P; excluded from valid discount
   PRICE           current_price_outlier_candidates                       314                                                   IQR candidates retained
   PRICE                    complete_price_rate_pct                     100.0                                         Valid price / all snapshots * 100
   PRICE           overall_observed_price_range_vnd                 3155000.0                      Descriptive catalog range only; not cross-source gap
MATCHING                        matching_candidates                       151                 Observed matching file; not a formal matching denominator
MATCHING                     verified_by_human_true                         0                 Observed matching file; not a formal matching denominator
MATCHING                    verified_by_human_false                       151                 Observed matching file; not a formal matching denominator
MATCHING                  matched_and_verified_rows                         0                 Observed matching file; not a formal matching denominator
MATCHING          verified_comparable_product_dates                         0                 Observed matching file; not a formal matching denominator
  REVIEW                                      total                      6673 Review analysis scope: Hasaki and Guardian; independent of price metrics.
  REVIEW                                   products                       749 Review analysis scope: Hasaki and Guardian; independent of price metrics.
  REVIEW                                       mean                   4.89982 Review analysis scope: Hasaki and Guardian; independent of price metrics.
  REVIEW                                     median                       5.0 Review analysis scope: Hasaki and Guardian; independent of price metrics.
  REVIEW                                  purchased                  0.744942 Review analysis scope: Hasaki and Guardian; independent of price metrics.
  REVIEW                                     images                  0.161696 Review analysis scope: Hasaki and Guardian; independent of price metrics.
  REVIEW                                    unknown                       410 Review analysis scope: Hasaki and Guardian; independent of price metrics.
  REVIEW                               unknown_rate                  0.061442 Review analysis scope: Hasaki and Guardian; independent of price metrics.
MATCHING                       match_status=pending                       130                    Denominator=151; percentage=86.0927%; missing retained
MATCHING                match_status=pending_review                        21                    Denominator=151; percentage=13.9073%; missing retained
MATCHING                    verified_by_human=False                       151                   Denominator=151; percentage=100.0000%; missing retained
  REVIEW           content_quality=usable_candidate                       338                    Denominator=410; percentage=82.4390%; missing retained
  REVIEW                      content_quality=short                        51                    Denominator=410; percentage=12.4390%; missing retained
  REVIEW            content_quality=low_information                        20                     Denominator=410; percentage=4.8780%; missing retained
  REVIEW            content_quality=selling_or_spam                         1                     Denominator=410; percentage=0.2439%; missing retained
  REVIEW                              is_bought=yes                       410                   Denominator=410; percentage=100.0000%; missing retained
  REVIEW                           has_images=False                       365                    Denominator=410; percentage=89.0244%; missing retained
  REVIEW                            has_images=True                        45                    Denominator=410; percentage=10.9756%; missing retained
  REVIEW                   product_id_match=unknown                       410                   Denominator=410; percentage=100.0000%; missing retained
  REVIEW                       category=Sữa rửa mặt                       113                    Denominator=410; percentage=27.5610%; missing retained
  REVIEW                         category=Tẩy trang                        82                    Denominator=410; percentage=20.0000%; missing retained
  REVIEW                             category=Serum                        75                    Denominator=410; percentage=18.2927%; missing retained
  REVIEW                    category=Kem chống nắng                        71                    Denominator=410; percentage=17.3171%; missing retained
  REVIEW                           category=Sữa tắm                        49                    Denominator=410; percentage=11.9512%; missing retained
  REVIEW            category=Tẩy tế bào chết cơ thể                        20                     Denominator=410; percentage=4.8780%; missing retained
  REVIEW           content_quality=usable_candidate                      5522                   Denominator=6263; percentage=88.1686%; missing retained
  REVIEW            content_quality=selling_or_spam                       341                    Denominator=6263; percentage=5.4447%; missing retained
  REVIEW                      content_quality=short                       210                    Denominator=6263; percentage=3.3530%; missing retained
  REVIEW            content_quality=low_information                       146                    Denominator=6263; percentage=2.3312%; missing retained
  REVIEW content_quality=purchase_or_price_question                        44                    Denominator=6263; percentage=0.7025%; missing retained
  REVIEW                             is_bought=True                      4561                   Denominator=6263; percentage=72.8245%; missing retained
  REVIEW                            is_bought=False                      1702                   Denominator=6263; percentage=27.1755%; missing retained
  REVIEW                           has_images=False                      5229                   Denominator=6263; percentage=83.4903%; missing retained
  REVIEW                            has_images=True                      1034                   Denominator=6263; percentage=16.5097%; missing retained
  REVIEW                     product_id_match=match                      6263                  Denominator=6263; percentage=100.0000%; missing retained
  REVIEW                       category=Sữa rửa mặt                      1611                   Denominator=6263; percentage=25.7225%; missing retained
  REVIEW                    category=Kem chống nắng                      1530                   Denominator=6263; percentage=24.4292%; missing retained
  REVIEW                             category=Serum                      1356                   Denominator=6263; percentage=21.6510%; missing retained
  REVIEW                         category=Tẩy trang                       999                   Denominator=6263; percentage=15.9508%; missing retained
  REVIEW                   category=Tẩy tế bào chết                       441                    Denominator=6263; percentage=7.0414%; missing retained
  REVIEW                           category=Sữa tắm                       203                    Denominator=6263; percentage=3.2413%; missing retained
  REVIEW         category=Sữa tắm | Tẩy tế bào chết                        74                    Denominator=6263; percentage=1.1815%; missing retained
  REVIEW             category=Sữa rửa mặt | Sữa tắm                        20                    Denominator=6263; percentage=0.3193%; missing retained
  REVIEW           category=Sữa rửa mặt | Tẩy trang                        14                    Denominator=6263; percentage=0.2235%; missing retained
  REVIEW      category=Kem chống nắng | Sữa rửa mặt                         6                    Denominator=6263; percentage=0.0958%; missing retained
  REVIEW                 category=Serum | Tẩy trang                         3                    Denominator=6263; percentage=0.0479%; missing retained
  REVIEW        category=Kem chống nắng | Tẩy trang                         3                    Denominator=6263; percentage=0.0479%; missing retained
  REVIEW            category=Kem chống nắng | Serum                         3                    Denominator=6263; percentage=0.0479%; missing retained
  REVIEW                       earliest_review_date                2017-01-11                                   Source review date; not collection date
  REVIEW                         latest_review_date                2026-10-21                                   Source review date; not collection date
  REVIEW                             missing_rating                         0                                                             Blank/NA only
  REVIEW                        missing_review_text                         0                                                             Blank/NA only
  REVIEW                        missing_review_date                         0                                                             Blank/NA only
  REVIEW                        invalid_review_date                         0                                                   Nonblank parse failures
  REVIEW                          duplicate_reviews                         0                          Excess duplicates using source+product+review ID
  REVIEW                        duplicate_flag_true                         0                                       Raw duplicate flag; no rows removed

            Nhóm                Giá trị  Snapshot  Giá hợp lệ  Thiếu/sai  Tỷ lệ thiếu/sai  Min (VND)  Max (VND)   Trung bình  Trung vị         Q1         Q3        IQR  Ứng viên ngoại lệ
   retailer_name                Cocolux       734         734          0              0.0     5000.0  3160000.0 3.848012e+05  299000.0  179250.00  492250.00  313000.00                 35
   retailer_name               Guardian       994         994          0              0.0    31000.0  3160000.0 3.228204e+05  247500.0  152000.00  412750.00  260750.00                 43
   retailer_name                 Hasaki      1871        1871          0              0.0     9000.0  2625000.0 2.964594e+05  227000.0  132500.00  360000.00  227500.00                135
   retailer_name     The Gioi Skin Food       500         500          0              0.0    24000.0  1409000.0 2.791000e+05  231500.0  136750.00  376500.00  239750.00                 16
   retailer_name                Watsons      2251        2251          0              0.0    17000.0  2963000.0 3.174234e+05  249000.0  144000.00  418000.00  274000.00                 90
primary_category         Kem chống nắng      1049        1049          0              0.0     9000.0  2625000.0 3.234820e+05  289000.0  169000.00  431000.00  262000.00                 20
primary_category                  Serum      1121        1121          0              0.0    20000.0  3160000.0 4.906780e+05  397000.0  240000.00  598000.00  358000.00                 77
primary_category            Sữa rửa mặt      1043        1043          0              0.0     9000.0  1632000.0 2.391663e+05  179000.0   99000.00  340000.00  241000.00                 29
primary_category                Sữa tắm       942         942          0              0.0     9000.0  2686000.0 2.224826e+05  186000.0  135000.00  260000.00  125000.00                 64
primary_category              Tẩy trang       640         640          0              0.0     5000.0  1449000.0 2.394555e+05  195000.0  116500.00  322250.00  205750.00                 22
primary_category        Tẩy tế bào chết       293         293          0              0.0    20000.0  1715000.0 2.315392e+05  177000.0  123000.00  297000.00  174000.00                 12
primary_category   Chưa phân loại/thiếu      1262        1262          0              0.0    18000.0  2612000.0 3.506886e+05  287000.0  166000.00  439000.00  273000.00                 70
           brand                16PLAIN         1           1          0              0.0    25000.0    25000.0 2.500000e+04   25000.0   25000.00   25000.00       0.00                  0
           brand                    3CE         1           1          0              0.0   379000.0   379000.0 3.790000e+05  379000.0  379000.00  379000.00       0.00                  0
           brand               9 Wishes         9           9          0              0.0   215000.0   435000.0 3.003333e+05  299000.0  249000.00  332000.00   83000.00                  0
           brand                9Wishes        10          10          0              0.0    49000.0   425000.0 2.477000e+05  244000.0  199500.00  291500.00   92000.00                  1
           brand                A Bonne         4           4          0              0.0    29000.0   167000.0 6.350000e+04   29000.0   29000.00   63500.00   34500.00                  1
           brand                A-Derma         3           3          0              0.0   310000.0   418000.0 3.460000e+05  310000.0  310000.00  364000.00   54000.00                  0
           brand                   ABIB        19          19          0              0.0   311000.0   699000.0 4.527368e+05  444000.0  365500.00  504500.00  139000.00                  0
           brand                 ABONNE         6           6          0              0.0    30000.0    30000.0 3.000000e+04   30000.0   30000.00   30000.00       0.00                  0
           brand                  ACNES        49          49          0              0.0    29000.0   392000.0 1.210000e+05   77000.0   65000.00  118000.00   53000.00                  7
           brand                AESTURA         6           6          0              0.0   150000.0   720000.0 4.285000e+05  364000.0  298000.00  613750.00  315750.00                  0
           brand                    AHC         3           3          0              0.0   436000.0  1208000.0 7.206667e+05  518000.0  477000.00  863000.00  386000.00                  0
           brand              ALGEMARIN         2           2          0              0.0   119000.0   165000.0 1.420000e+05  142000.0  130500.00  153500.00   23000.00                  0
           brand               AMORTALS         1           1          0              0.0   211000.0   211000.0 2.110000e+05  211000.0  211000.00  211000.00       0.00                  0
           brand                 ANESSA        72          72          0              0.0   109000.0  1430000.0 5.270278e+05  474000.0  358000.00  668000.00  310000.00                  2
           brand                   ANUA        16          16          0              0.0   275000.0   630000.0 4.353125e+05  431000.0  340000.00  487750.00  147750.00                  0
           brand                APERIRE         2           2          0              0.0   384000.0   384000.0 3.840000e+05  384000.0  384000.00  384000.00       0.00                  0
           brand                  ARIUL         5           5          0              0.0    22000.0    48000.0 2.980000e+04   22000.0   22000.00   35000.00   13000.00                  0
           brand              AROMATICA         7           7          0              0.0    90000.0   530000.0 3.282857e+05  281000.0  234000.00  464500.00  230500.00                  0
           brand                ARRAHAN         9           9          0              0.0    89000.0   109000.0 9.677778e+04   99000.0   89000.00   99000.00   10000.00                  0
           brand                   AURA         2           2          0              0.0    49000.0    49000.0 4.900000e+04   49000.0   49000.00   49000.00       0.00                  0
           brand                  AVENE         7           7          0              0.0   146000.0   793000.0 3.111429e+05  272000.0  170000.00  313500.00  143500.00                  1
           brand                 AXIS-Y        21          21          0              0.0   268000.0   556000.0 4.415714e+05  483000.0  369000.00  529000.00  160000.00                  0
           brand                AZARINE         1           1          0              0.0   105000.0   105000.0 1.050000e+05  105000.0  105000.00  105000.00       0.00                  0
           brand                AZDERMA        19          19          0              0.0    74000.0   306000.0 1.598421e+05  175000.0   94000.00  175000.00   81000.00                  1
           brand                Actidem        13          13          0              0.0   141000.0   290000.0 1.842308e+05  159000.0  155000.00  190000.00   35000.00                  2
           brand                  Adiva         1           1          0              0.0   149000.0   149000.0 1.490000e+05  149000.0  149000.00  149000.00       0.00                  0
           brand         Angel's Liquid        15          15          0              0.0   255000.0  1148000.0 6.178667e+05  487000.0  419000.00  831500.00  412500.00                  0
           brand                Avander         3           3          0              0.0    23000.0    95000.0 6.233333e+04   69000.0   46000.00   82000.00   36000.00                  0
           brand                 Avatar         7           7          0              0.0    54000.0   189000.0 1.228571e+05  118000.0   99000.00  150500.00   51500.00                  0
           brand                  Avène         4           4          0              0.0   311000.0   467000.0 3.845000e+05  380000.0  318500.00  446000.00  127500.00                  0
           brand                  B.O.M        40          40          0              0.0     9000.0   689000.0 2.879750e+05  251500.0  191750.00  406000.00  214250.00                  0
           brand                   BABE         1           1          0              0.0   379000.0   379000.0 3.790000e+05  379000.0  379000.00  379000.00       0.00                  0
           brand            BABY BRIGHT         8           8          0              0.0    25000.0   139000.0 1.122500e+05  129000.0  116500.00  131500.00   15000.00                  2
           brand                 BADLAB         2           2          0              0.0   215000.0   350000.0 2.825000e+05  282500.0  248750.00  316250.00   67500.00                  0
           brand                BALANCE         2           2          0              0.0   308000.0   308000.0 3.080000e+05  308000.0  308000.00  308000.00       0.00                  0
           brand            BANANA BOAT        23          23          0              0.0   122000.0   349000.0 2.437826e+05  259000.0  174500.00  317000.00  142500.00                  0
           brand              BANILA CO        26          26          0              0.0    95000.0   545000.0 3.615000e+05  336000.0  303000.00  399000.00   96000.00                  2
           brand               BANOBAGI        14          14          0              0.0    20000.0    22000.0 2.014286e+04   20000.0   20000.00   20000.00       0.00                  1
           brand       BEAUTY OF JOSEON         6           6          0              0.0   255000.0   391000.0 3.270000e+05  335000.0  275000.00  377000.00  102000.00                  0
           brand                  BELIF         8           8          0              0.0   445000.0   874000.0 7.092500e+05  770000.0  609000.00  805750.00  196750.00                  0
           brand            BELLE FLORA         3           3          0              0.0    60000.0   100000.0 7.933333e+04   78000.0   69000.00   89000.00   20000.00                  0
           brand                  BENEW         1           1          0              0.0    78000.0    78000.0 7.800000e+04   78000.0   78000.00   78000.00       0.00                  0
           brand                 BENZAC         5           5          0              0.0   147000.0   684000.0 4.142000e+05  307000.0  294000.00  639000.00  345000.00                  0
           brand                BEPLAIN        53          53          0              0.0   119000.0   712000.0 3.741321e+05  398000.0  299000.00  450000.00  151000.00                  1
           brand                 BEYOND        10          10          0              0.0    55000.0   520000.0 3.008000e+05  316500.0  269250.00  343500.00   74250.00                  2
           brand               BIELENDA         2           2          0              0.0   289000.0   289000.0 2.890000e+05  289000.0  289000.00  289000.00       0.00                  0
           brand                BIFESTA        16          16          0              0.0    47000.0   194000.0 1.148750e+05  128000.0   47000.00  150750.00  103750.00                  0
           brand               BIODERMA       111         111          0              0.0    99000.0   980000.0 4.548108e+05  405000.0  340000.00  540000.00  200000.00                  5
           brand                  BIORE        62          62          0              0.0    28000.0   318000.0 1.582097e+05  130000.0   66000.00  235500.00  169500.00                  0
           brand                  BIORÉ        46          46          0              0.0    26000.0   279000.0 1.285870e+05  107000.0   62500.00  196000.00  133500.00                  0
           brand               BIOVERSE        10          10          0              0.0   138000.0   291000.0 2.088000e+05  192000.0  192000.00  236000.00   44000.00                  0
           brand                   BNBG         7           7          0              0.0    28000.0   299000.0 9.314286e+04   39000.0   39000.00  104000.00   65000.00                  1
           brand                  BOBBY         2           2          0              0.0    52000.0    52000.0 5.200000e+04   52000.0   52000.00   52000.00       0.00                  0
           brand                    BOM        35          35          0              0.0   254000.0   688000.0 4.198857e+05  406000.0  286000.00  523500.00  237500.00                  0
           brand            BRING GREEN        12          12          0              0.0   179000.0   538000.0 3.189167e+05  319000.0  194000.00  390750.00  196750.00                  0
           brand                 BROWIT         3           3          0              0.0   122000.0   169000.0 1.410000e+05  132000.0  127000.00  150500.00   23500.00                  0
           brand                    BSC         2           2          0              0.0    49000.0    49000.0 4.900000e+04   49000.0   49000.00   49000.00       0.00                  0
           brand               BY MERZY         1           1          0              0.0   234000.0   234000.0 2.340000e+05  234000.0  234000.00  234000.00       0.00                  0
           brand               BYPHASSE         5           5          0              0.0    52000.0  1140000.0 3.110000e+05  119000.0  109000.00  135000.00   26000.00                  2
           brand                    BYS         2           2          0              0.0   296000.0   296000.0 2.960000e+05  296000.0  296000.00  296000.00       0.00                  0
           brand    BYVIBES WONDER BATH         1           1          0              0.0   189000.0   189000.0 1.890000e+05  189000.0  189000.00  189000.00       0.00                  0
           brand                BZU BZU         1           1          0              0.0   112000.0   112000.0 1.120000e+05  112000.0  112000.00  112000.00       0.00                  0
           brand Balance Active Formula        18          18          0              0.0    31000.0   250000.0 1.560000e+05  154000.0  154000.00  168000.00   14000.00                  5
           brand               BareSoul        19          19          0              0.0    83000.0   410000.0 1.863158e+05  179000.0  128000.00  231500.00  103500.00                  1
           brand                Besilki         2           2          0              0.0    72000.0    72000.0 7.200000e+04   72000.0   72000.00   72000.00       0.00                  0
           brand            Bio-essence        96          96          0              0.0    39000.0   707000.0 1.782240e+05  140000.0  110250.00  208000.00   97750.00                  9
           brand        Bye Bye Blemish         6           6          0              0.0   195000.0   748000.0 3.570000e+05  299000.0  219750.00  380500.00  160750.00                  1
           brand         CANCER COUNCIL        14          14          0              0.0    96000.0   416000.0 3.048571e+05  306500.0  283000.00  384750.00  101750.00                  1
           brand               CARE:NEL        14          14          0              0.0    55000.0   424000.0 1.887143e+05  237500.0   63500.00  258750.00  195250.00                  0
           brand          CARRIE JUNIOR         5           5          0              0.0   148000.0   382000.0 2.898000e+05  382000.0  155000.00  382000.00  227000.00                  0
           brand               CARYOPHY        18          18          0              0.0   213000.0   618000.0 3.350000e+05  291500.0  266250.00  341250.00   75000.00                  4
           brand             CATHY DOLL         4           4          0              0.0    75000.0   159000.0 1.262500e+05  135500.0  110250.00  151500.00   41250.00                  0
           brand                CATRICE         1           1          0              0.0   239000.0   239000.0 2.390000e+05  239000.0  239000.00  239000.00       0.00                  0
           brand                CELIMAX        20          20          0              0.0   227000.0   768000.0 4.165000e+05  389500.0  309000.00  489500.00  180500.00                  1
           brand                 CELLIO         1           1          0              0.0    95000.0    95000.0 9.500000e+04   95000.0   95000.00   95000.00       0.00                  0
           brand                 CERAVE       101         101          0              0.0    25000.0   535000.0 2.893465e+05  315000.0  186000.00  359000.00  173000.00                  0
           brand                 CHANDO        22          22          0              0.0   201000.0   800000.0 5.399545e+05  554000.0  439000.00  693000.00  254000.00                  0
           brand                  CINDY         7           7          0              0.0   120000.0   160000.0 1.467143e+05  147000.0  140000.00  160000.00   20000.00                  0
           brand            CINDY BLOOM        13          13          0              0.0    70000.0   239000.0 1.522308e+05  154000.0  120000.00  175000.00   55000.00                  0
           brand                  CLEAR         3           3          0              0.0   171000.0   200000.0 1.903333e+05  200000.0  185500.00  200000.00   14500.00                  0
           brand               CLINICOS        18          18          0              0.0    74000.0   687000.0 4.005556e+05  408000.0  276000.00  525750.00  249750.00                  0
           brand                   CLIO         2           2          0              0.0   239000.0   365000.0 3.020000e+05  302000.0  270500.00  333500.00   63000.00                  0
           brand               CLOSE UP         8           8          0              0.0    95000.0   197001.0 1.371254e+05  137500.5  126750.00  143250.75   16500.75                  2
           brand                   CLÉO         6           6          0              0.0   100000.0   159000.0 1.438333e+05  151000.0  143000.00  159000.00   16000.00                  1
           brand                    CNP        14          14          0              0.0   360000.0  1030000.0 5.751429e+05  521500.0  485500.00  627500.00  142000.00                  1
           brand         CNP LABORATORY        17          17          0              0.0   332000.0   810000.0 5.722353e+05  569000.0  515000.00  659000.00  144000.00                  0
           brand                  COAST         5           5          0              0.0    28000.0   199000.0 1.296000e+05  123000.0  109000.00  189000.00   80000.00                  0
           brand                 COBOTÉ         5           5          0              0.0   110000.0   323000.0 1.978000e+05  161000.0  113000.00  282000.00  169000.00                  0
           brand                COLGATE         4           4          0              0.0    47000.0   462000.0 2.397500e+05  225000.0  170750.00  294000.00  123250.00                  0
           brand    COLLAGEN BY WATSONS        18          18          0              0.0   159000.0   319000.0 2.390000e+05  239000.0  159000.00  319000.00  160000.00                  0
           brand               COLORKEY        39          39          0              0.0     5000.0   396000.0 1.332308e+05  145000.0   88500.00  165000.00   76500.00                  1
           brand             COMPLIMENT        27          27          0              0.0    71000.0   116000.0 9.655556e+04   95000.0   88000.00  105000.00   17000.00                  0
           brand                  COOPY        12          12          0              0.0   450000.0   880000.0 6.275000e+05  700000.0  500000.00  700000.00  200000.00                  0

## Ngoại lệ và cách xử lý
Ứng viên nằm ngoài Q1−1,5×IQR hoặc Q3+1,5×IQR chỉ được đánh dấu. Không tự xóa hoặc sửa vì mức giá có thể khác do thương hiệu, dung tích, quy cách hoặc phân khúc. CSV nguồn được giữ nguyên.

In [5]:
print('Ứng viên ngoại lệ:',len(g['outlier_rows']))
pd.DataFrame(g['outlier_rows'],columns=['snapshot_id','product_id','retailer','danh mục','thương hiệu','collected_at','current_price_vnd','listed_price_vnd','source_file']).head(20)

Ứng viên ngoại lệ: 314

          snapshot_id            product_id retailer        danh mục    thương hiệu              collected_at  current_price_vnd  listed_price_vnd                     source_file
snap_3d2bdacfb8eb621a prod_063773a059be6c88  Cocolux           Serum          LUVUM 2026-10-21T08:13:42+07:00             858000               NaN       cocolux_serum_page_4.html
snap_ebbf45c33e7b80a5 prod_09e3d594f5453049  Cocolux Tẩy tế bào chết          OBAGI 2026-10-21T08:49:39+07:00             960000               NaN cocolux_exfoliators_page_2.html
snap_a5dae9a4055c7125 prod_0c57fdc664fad36c  Cocolux           Serum            SVR 2026-10-21T08:13:42+07:00             989000         1099000.0       cocolux_serum_page_4.html
snap_f965599aac5d59be prod_1e41a928ba8a87c4  Cocolux           Serum         oh!oh! 2026-10-21T08:13:42+07:00             799000          980000.0       cocolux_serum_page_4.html
snap_6cf36f0f0c64d511 prod_1f91dab13d8e80cc  Cocolux  Kem chống nắng      Martiderm 2026-10-21T07:33:02+07:00             799000         1380000.0  cocolux_sunscreens_page_4.html
snap_d8de2429a6c2da76 prod_1fb73102de10798a  Cocolux  Kem chống nắng      Martiderm 2026-10-21T07:33:02+07:00             799000         1380000.0  cocolux_sunscreens_page_4.html
snap_18be95ac82913c34 prod_22ddd5c4db44a178  Cocolux           Serum            SVR 2026-10-21T08:13:42+07:00             999000         1119000.0       cocolux_serum_page_4.html
snap_54c63db823ae4c78 prod_24556a95c97aeeca  Cocolux           Serum PAULA'S CHOICE 2026-10-21T08:13:42+07:00            1640000         2050000.0       cocolux_serum_page_4.html
snap_ac47149773a4adc5 prod_31877a45738ce914  Cocolux           Serum          OBAGI 2026-10-21T08:13:42+07:00            2338000         2750000.0       cocolux_serum_page_4.html
snap_3dbdcc0cafc08a25 prod_323a89293b9310e8  Cocolux           Serum La Roche-Posay 2026-10-21T08:13:42+07:00            1550000               NaN       cocolux_serum_page_4.html
snap_3e4ba6d1dec31ef8 prod_3a4990c6c791fbc3  Cocolux Tẩy tế bào chết PAULA'S CHOICE 2026-10-21T08:49:39+07:00             927000         1030000.0 cocolux_exfoliators_page_2.html
snap_b53f6bcc6278fde0 prod_3f61bd03bfe61756  Cocolux           Serum            SVR 2026-10-21T08:13:42+07:00             989000         1099000.0       cocolux_serum_page_4.html
snap_5e3be886a77f7a85 prod_3f69b69202908b1e  Cocolux           Serum       THE WHOO 2026-10-21T08:13:42+07:00            1699000         1900000.0       cocolux_serum_page_4.html
snap_03f6f219acbb3311 prod_4adace7ea3b15f58  Cocolux       Tẩy trang     Shu Uemura 2026-10-21T08:35:28+07:00            1310000         1380000.0   cocolux_tay_trang_page_3.html
snap_49fd43235aa6ba74 prod_4c2002fbab19d08e  Cocolux           Serum PAULA'S CHOICE 2026-10-21T08:13:42+07:00            1672000         2090000.0       cocolux_serum_page_4.html
snap_665ffe16d5c60c9f prod_4cad1337ca47b9b9  Cocolux           Serum          Vichy 2026-10-21T08:13:42+07:00            1229000         1350000.0       cocolux_serum_page_4.html
snap_e0553f77d0263247 prod_57f1ec9f0d4df555  Cocolux           Serum          OBAGI 2026-10-21T08:13:42+07:00            3160000         3950000.0       cocolux_serum_page_4.html
snap_e813e41e2ce5c8d5 prod_5824d270acb1af47  Cocolux           Serum La Roche-Posay 2026-10-21T08:13:42+07:00            1170000               NaN       cocolux_serum_page_4.html
snap_e79548a879578518 prod_5c108fc63466c78e  Cocolux Tẩy tế bào chết PAULA'S CHOICE 2026-10-21T08:49:39+07:00             852000         1065000.0 cocolux_exfoliators_page_2.html
snap_a68078de97e21e6e prod_6084db0db3328a32  Cocolux           Serum          Vichy 2026-10-21T08:13:42+07:00            1290000         1450000.0       cocolux_serum_page_4.html

## Review Hasaki và Guardian độc lập
Đọc cả hasaki_reviews.csv và guardian_reviews.csv, giữ nguyên dòng nguồn. Thống kê tổng và từng nguồn; sản phẩm đếm theo cặp source + source_product_id để tránh trùng mã giữa nhà bán lẻ. Rating kiểm tra 1–5, giữ nửa sao. Ngày Hasaki kèm giờ và ngày Guardian tiếng Việt được đọc theo định dạng riêng, không dùng làm collected_at. Giữ nhãn category nguồn; cờ product_id_match chưa xác minh liên kết với bảng giá.
Bảng chất lượng theo source giữ tất cả dòng, phân biệt missing và invalid; duplicate là số dòng dư theo source + source_product_id + review_id. Source product-match flag: this source field is NOT a verified link to price products. Các giá trị và số lượng thực tế nằm trong bảng categorical theo từng nguồn. Rating là observed rating distribution in the collected sample; không suy rộng toàn bộ khách hàng. Tỷ trọng nguồn có trong sample_share; pooled metrics không phải so sánh cân bằng hai retailer, cần xem per-source metrics.

In [6]:
display(pd.DataFrame(g['review_summary_rows']).rename(columns={'unknown':'source_flag_unknown_n','unknown_rate':'source_flag_unknown_rate'}))
display(g['review_source_quality_frame'])
display(g['review_quality'])
print('Review date:',g['reviews']['review_date_parsed'].min(),g['reviews']['review_date_parsed'].max())
p=g['price'][g['valid_price']]
print(f'Giá hiện tại: n={len(p)}, min={p.min():,.0f} VND, max={p.max():,.0f} VND, mean={p.mean():,.2f} VND, median={p.median():,.0f} VND.')
print('Ứng viên IQR được giữ nguyên:',int(g['outlier_flag'].sum()))
print('Anomalous discount L<P:',int(g['anomalous_discount'].sum()))

Review date: 2017-01-11 03:50:11 2026-10-21 00:00:00
Giá hiện tại: n=6350, min=5,000 VND, max=3,160,000 VND, mean=316,861.91 VND, median=244,000 VND.
Ứng viên IQR được giữ nguyên: 314
Anomalous discount L<P: 0

  source  total  products     mean  median  purchased   images  source_flag_unknown_n  source_flag_unknown_rate  sample_share
     all   6673       749 4.899820     5.0   0.744942 0.161696                    410                  0.061442      1.000000
guardian    410       193 4.928049     5.0   1.000000 0.109756                    410                  1.000000      0.061442
  hasaki   6263       556 4.897972     5.0   0.728245 0.165097                      0                  0.000000      0.938558

  source  total_reviews  unique_source_products  valid_rating_n  missing_rating_n  invalid_rating_n  min_rating  max_rating  mean_rating  median_rating  missing_review_text_n  missing_review_date_n  invalid_review_date_n  duplicate_review_n  is_bought_known_n  is_bought_true_n  has_images_known_n  has_images_true_n product_id_match_counts  sample_share
guardian            410                     193             410                 0                 0         2.5         5.0     4.928049            5.0                      0                      0                      0                   0                410               410                 410                 45        {"unknown": 410}      0.061442
  hasaki           6263                     556            6263                 0                 0         4.0         5.0     4.897972            5.0                      0                      0                      0                   0               6263              4561                6263               1034         {"match": 6263}      0.938558

          source         variable                        value  count  percentage  unique_count  denominator_n
guardian_reviews  content_quality             usable_candidate    338   82.439024             4            410
guardian_reviews  content_quality                        short     51   12.439024             4            410
guardian_reviews  content_quality              low_information     20    4.878049             4            410
guardian_reviews  content_quality              selling_or_spam      1    0.243902             4            410
guardian_reviews        is_bought                          yes    410  100.000000             1            410
guardian_reviews       has_images                        False    365   89.024390             2            410
guardian_reviews       has_images                         True     45   10.975610             2            410
guardian_reviews product_id_match                      unknown    410  100.000000             1            410
guardian_reviews         category                  Sữa rửa mặt    113   27.560976             6            410
guardian_reviews         category                    Tẩy trang     82   20.000000             6            410
guardian_reviews         category                        Serum     75   18.292683             6            410
guardian_reviews         category               Kem chống nắng     71   17.317073             6            410
guardian_reviews         category                      Sữa tắm     49   11.951220             6            410
guardian_reviews         category       Tẩy tế bào chết cơ thể     20    4.878049             6            410
  hasaki_reviews  content_quality             usable_candidate   5522   88.168609             5           6263
  hasaki_reviews  content_quality              selling_or_spam    341    5.444675             5           6263
  hasaki_reviews  content_quality                        short    210    3.353026             5           6263
  hasaki_reviews  content_quality              low_information    146    2.331151             5           6263
  hasaki_reviews  content_quality   purchase_or_price_question     44    0.702539             5           6263
  hasaki_reviews        is_bought                         True   4561   72.824525             2           6263
  hasaki_reviews        is_bought                        False   1702   27.175475             2           6263
  hasaki_reviews       has_images                        False   5229   83.490340             2           6263
  hasaki_reviews       has_images                         True   1034   16.509660             2           6263
  hasaki_reviews product_id_match                        match   6263  100.000000             1           6263
  hasaki_reviews         category                  Sữa rửa mặt   1611   25.722497            13           6263
  hasaki_reviews         category               Kem chống nắng   1530   24.429187            13           6263
  hasaki_reviews         category                        Serum   1356   21.650966            13           6263
  hasaki_reviews         category                    Tẩy trang    999   15.950822            13           6263
  hasaki_reviews         category              Tẩy tế bào chết    441    7.041354            13           6263
  hasaki_reviews         category                      Sữa tắm    203    3.241258            13           6263
  hasaki_reviews         category    Sữa tắm | Tẩy tế bào chết     74    1.181542            13           6263
  hasaki_reviews         category        Sữa rửa mặt | Sữa tắm     20    0.319336            13           6263
  hasaki_reviews         category      Sữa rửa mặt | Tẩy trang     14    0.223535            13           6263
  hasaki_reviews         category Kem chống nắng | Sữa rửa mặt      6    0.095801            13           6263
  hasaki_reviews         category            Serum | Tẩy trang      3    0.047900            13           6263
  hasaki_reviews         category   Kem chống nắng | Tẩy trang      3    0.047900            13           6263
  hasaki_reviews         category       Kem chống nắng | Serum      3    0.047900            13           6263

## Nhận xét và giới hạn
Kết quả chỉ phản ánh các nhà bán lẻ và thời gian trong dữ liệu. Thống kê theo retailer hoặc danh mục mô tả observed catalog/snapshot price level; chưa chứng minh nơi bán rẻ hơn cho cùng sản phẩm. Chưa có verified equivalent match, chưa có mẫu số matching chính thức. Review Hasaki và Guardian được phân tích độc lập và không dùng để suy luận quan hệ giá–rating. Ngoại lệ giữ lại để kiểm tra thương hiệu, dung tích và quy cách; không tự loại bỏ.